// Mock data for CatBus public pages

export const networkStats = {
  nodesOnline: 12,
  skillsAvailable: 47,
  callsToday: 1205,
  avgResponseTime: 89,
};

export const topSkills = [
  { name: "translate", providers: 3, callsToday: 156, avgLatency: 148 },
  { name: "json_format", providers: 2, callsToday: 89, avgLatency: 52 },
  { name: "echo", providers: 4, callsToday: 67, avgLatency: 35 },
  { name: "text_stats", providers: 2, callsToday: 45, avgLatency: 41 },
  { name: "summarize", providers: 3, callsToday: 38, avgLatency: 210 },
  { name: "image_compress", providers: 1, callsToday: 29, avgLatency: 320 },
  { name: "sentiment", providers: 2, callsToday: 24, avgLatency: 95 },
  { name: "code_review", providers: 1, callsToday: 18, avgLatency: 450 },
];

export const onlineNodes = [
  {
    name: "gouzai",
    nodeId: "0df18901909a",
    skillCount: 4,
    uptime: "2h 15m",
    status: "online" as const,
    skills: ["translate", "text_stats", "json_format", "echo"],
  },
  {
    name: "xiaohe",
    nodeId: "6f72bc3e41d7",
    skillCount: 4,
    uptime: "2h 10m",
    status: "online" as const,
    skills: ["translate", "echo", "summarize", "sentiment"],
  },
  {
    name: "node-3",
    nodeId: "a1b2c3d4e5f6",
    skillCount: 2,
    uptime: "45m",
    status: "online" as const,
    skills: ["json_format", "echo"],
  },
  {
    name: "gpu-worker-1",
    nodeId: "8e9f0a1b2c3d",
    skillCount: 3,
    uptime: "6h 32m",
    status: "online" as const,
    skills: ["image_compress", "summarize", "code_review"],
  },
  {
    name: "relay-east",
    nodeId: "4d5e6f708192",
    skillCount: 5,
    uptime: "12h 48m",
    status: "online" as const,
    skills: ["translate", "echo", "json_format", "text_stats", "sentiment"],
  },
  {
    name: "dev-box",
    nodeId: "c3d4e5f6a7b8",
    skillCount: 2,
    uptime: "1h 5m",
    status: "online" as const,
    skills: ["echo", "text_stats"],
  },
];

export const skillList = [
  {
    name: "translate",
    description: "Translate text to target language using LLM",
    providers: 3,
    callsToday: 156,
    avgLatency: 148,
    category: "Translation",
    status: "online" as const,
  },
  {
    name: "json_format",
    description: "Parse and format JSON with validation",
    providers: 2,
    callsToday: 89,
    avgLatency: 52,
    category: "Data",
    status: "online" as const,
  },
  {
    name: "echo",
    description: "Echo back input for testing connectivity",
    providers: 4,
    callsToday: 67,
    avgLatency: 35,
    category: "Utility",
    status: "online" as const,
  },
  {
    name: "text_stats",
    description: "Analyze text and return word count, char count, language",
    providers: 2,
    callsToday: 45,
    avgLatency: 41,
    category: "Data",
    status: "online" as const,
  },
  {
    name: "summarize",
    description: "Summarize long text into concise bullet points",
    providers: 3,
    callsToday: 38,
    avgLatency: 210,
    category: "Code",
    status: "online" as const,
  },
  {
    name: "image_compress",
    description: "Compress and optimize images with quality control",
    providers: 1,
    callsToday: 29,
    avgLatency: 320,
    category: "Media",
    status: "online" as const,
  },
  {
    name: "sentiment",
    description: "Detect sentiment and emotion in text",
    providers: 2,
    callsToday: 24,
    avgLatency: 95,
    category: "Data",
    status: "online" as const,
  },
  {
    name: "code_review",
    description: "Review code snippets for bugs and improvements",
    providers: 1,
    callsToday: 18,
    avgLatency: 450,
    category: "Code",
    status: "online" as const,
  },
  {
    name: "pdf_extract",
    description: "Extract text and metadata from PDF files",
    providers: 1,
    callsToday: 12,
    avgLatency: 280,
    category: "Data",
    status: "offline" as const,
  },
  {
    name: "speech_to_text",
    description: "Convert audio to text transcription",
    providers: 0,
    callsToday: 0,
    avgLatency: 0,
    category: "Media",
    status: "offline" as const,
  },
];

export const activityFeed = [
  { time: "12:03:45", caller: "gouzai", skill: "translate", provider: "xiaohe", latency: 148 },
  { time: "12:03:42", caller: "xiaohe", skill: "echo", provider: "gouzai", latency: 35 },
  { time: "12:03:38", caller: "node-3", skill: "json_format", provider: "xiaohe", latency: 52 },
  { time: "12:03:21", caller: "gpu-worker-1", skill: "summarize", provider: "relay-east", latency: 195 },
  { time: "12:03:15", caller: "relay-east", skill: "text_stats", provider: "gouzai", latency: 41 },
  { time: "12:02:58", caller: "dev-box", skill: "echo", provider: "node-3", latency: 28 },
  { time: "12:02:44", caller: "gouzai", skill: "sentiment", provider: "xiaohe", latency: 88 },
  { time: "12:02:30", caller: "xiaohe", skill: "translate", provider: "relay-east", latency: 162 },
  { time: "12:02:18", caller: "node-3", skill: "echo", provider: "gouzai", latency: 31 },
  { time: "12:02:05", caller: "gpu-worker-1", skill: "code_review", provider: "gpu-worker-1", latency: 430 },
];

export const skillCategories = [
  "All",
  "Translation",
  "Code",
  "Data",
  "Media",
  "Utility",
];
